[package]
name = "quick_xml_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
pretty_assertions = "1.3.0"
quick-xml = { version = "0.28.2", features = ["tokio", "serialize", "async-tokio"] }
serde = { version = "1.0.162", features = ["derive", "serde_derive"] }
zip = "0.6.5"
