[package]
name = "nlx"
version = "0.0.1"
author = "Paul Duvenage <duvenagep@gmail.com>"
about = "This is a simple CLI to parse the LVBAG Extract XMLs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-watch = "8.4.0"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.3.0", features = ["derive"] }
csv = "1.2.1"
geo = { version = "0.25.0", features = ["use-serde", "proj"] }
indicatif = "0.17.3"
pretty_assertions = "1.3.0"
proj = "0.27.0"
quick-xml = { version = "0.28.2", features = ["tokio", "serialize", "async-tokio"] }
rayon = "1.7.0"
serde = { version = "1.0.162", features = ["derive", "serde_derive"] }
wkt = { version = "0.10.3", features = ["serde"] }
zip = "0.6.5"
